---
- name: smoke test services
  hosts: frontends
  gather_facts: false
  vars:
    - correct_response: Tomcat on app
    - domain: example.opentlc.com  

  tasks:

  - name: check load balancers and app servers for expected response
    uri:
      url:  http://frontend.{{GUID }}.example.opentlc.com
      return_content: yes
    register: result
    until: '"Tomcat on app" in result.content'
    retries: 10
    delay: 1
